//! Opaque, encrypted pagination cursors.
//!
//! Raw DynamoDB keys must never leak to clients (`EVT#<millis>#<id>`
//! exposes table internals), so page tokens are Fernet-sealed via the
//! [`cursor_crypto`] crate (pure Rust, same wire format as
//! <https://github.com/fernet/spec>). Tokens look like
//! `h1.<base64url>` (`h1` = envelope version for future rotation) and are
//! opaque to the frontend, which just echoes them back.
//!
//! Key comes from the `CURSOR_FERNET_KEY` env var (base64url of 32 random
//! bytes, generated by Terraform).

use std::sync::OnceLock;

/// Envelope version prefix. Bump when the token format changes so old
/// tokens fail closed instead of decrypting as garbage.
const ENVELOPE_V1: &str = "h1.";
/// Cursors stay valid as long as a login session (matches refresh TTL).
const CURSOR_TTL_SECS: u64 = 30 * 24 * 3600;

#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum Error {
    #[error("cursor key not configured")]
    MissingKey,
    #[error("invalid cursor key")]
    InvalidKey,
    #[error("invalid or expired cursor")]
    InvalidCursor,
}

/// Percent-decode a query value (`%23` -> `#`, `+` -> space). API Gateway
/// forwards query values still-encoded and `req.uri().query()` does not decode
/// them, so a `%3D`-padded cursor must be decoded before opening.
pub fn url_decode(s: &str) -> String {
    fn hex_val(b: u8) -> Option<u8> {
        match b {
            b'0'..=b'9' => Some(b - b'0'),
            b'a'..=b'f' => Some(b - b'a' + 10),
            b'A'..=b'F' => Some(b - b'A' + 10),
            _ => None,
        }
    }

    let bytes = s.as_bytes();
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' && i + 2 < bytes.len() {
            if let (Some(h), Some(l)) = (hex_val(bytes[i + 1]), hex_val(bytes[i + 2])) {
                out.push(h << 4 | l);
                i += 3;
                continue;
            }
        }
        out.push(if bytes[i] == b'+' { b' ' } else { bytes[i] });
        i += 1;
    }
    String::from_utf8_lossy(&out).into_owned()
}

fn read_key() -> Result<[u8; 32], Error> {
    let raw = std::env::var("CURSOR_FERNET_KEY").map_err(|_| Error::MissingKey)?;
    cursor_crypto::decode_key(&raw).map_err(|_| Error::InvalidKey)
}

/// Seal a raw key with an explicit key (pure — unit-testable).
pub fn seal_with_key(key: &[u8; 32], plaintext: &str) -> String {
    format!(
        "{}{}",
        ENVELOPE_V1,
        cursor_crypto::encrypt(key, plaintext.as_bytes())
    )
}

/// Open a token with an explicit key (pure — unit-testable).
pub fn open_with_key(key: &[u8; 32], token: &str) -> Result<String, Error> {
    let inner = token.strip_prefix(ENVELOPE_V1).ok_or(Error::InvalidCursor)?;
    let bytes =
        cursor_crypto::decrypt(key, inner, CURSOR_TTL_SECS).map_err(|_| Error::InvalidCursor)?;
    String::from_utf8(bytes).map_err(|_| Error::InvalidCursor)
}

/// Seal a raw key (e.g. a DynamoDB `SK`) into an opaque page token.
pub fn seal_cursor(plaintext: &str) -> Result<String, Error> {
    Ok(seal_with_key(&read_key()?, plaintext))
}

/// Open a page token back into the raw key. Any failure (unknown envelope,
/// tampered token, expired TTL, missing key) is a single `InvalidCursor`
/// so callers map it to one error response.
pub fn open_cursor(token: &str) -> Result<String, Error> {
    open_with_key(&read_key()?, token)
}

/// Whether the env key parses (cached per cold start).
pub fn key_configured() -> bool {
    static CONFIGURED: OnceLock<bool> = OnceLock::new();
    *CONFIGURED.get_or_init(|| read_key().is_ok())
}

#[cfg(test)]
mod tests {
    use super::*;

    // Same spec key used by cursor-crypto's own vector tests.
    const TEST_KEY_B64: &str = "cw_0x689RpI-jtRR7oE8h_eQsKImvJapLeSbXpwF4e4=";

    fn test_key() -> [u8; 32] {
        cursor_crypto::decode_key(TEST_KEY_B64).unwrap()
    }

    #[test]
    fn round_trip_is_opaque() {
        let token = seal_with_key(&test_key(), "EVT#123#epi_456");
        assert!(token.starts_with("h1."));
        assert!(!token.contains("EVT#"));
        assert_eq!(open_with_key(&test_key(), &token).unwrap(), "EVT#123#epi_456");
    }

    #[test]
    fn garbage_fails_closed() {
        let key = test_key();
        assert_eq!(open_with_key(&key, "EVT#123#raw-key"), Err(Error::InvalidCursor));
        assert_eq!(open_with_key(&key, "h1.!!!"), Err(Error::InvalidCursor));
        assert_eq!(open_with_key(&key, "h2.abc"), Err(Error::InvalidCursor));
        // Sealed with another key must not open.
        let other = seal_with_key(&[7u8; 32], "EVT#123#epi_456");
        assert_eq!(open_with_key(&key, &other), Err(Error::InvalidCursor));
    }
}
